
//POST ACTIONS
export const FETCH_POSTS = 'FETCH_POSTS'
export const NEW_POST = 'NEW_POST'
export const DELETE_POST = "DELETE_POST"
export const UPDATE_POST = "UPDATE_POST"

//STOCK ACTIONS
export const FETCH_STOCKS = 'FETCH_STOCKS'
export const FETCH_TICKERS = 'FETCH_TICKERS'
export const ADD_LIST_STOCK = 'ADD_LIST_STOCK'

//LOGIN ACTIONS
export const LOGIN_USER = "LOGIN_USER"
export const LOGOUT_USER = "LOGOUT_USER"


//STOCK_LIST_ACTIONS
export const ADD_STOCK_TO_LIST = "ADD_STOCK_TO_LIST"
export const REMOVE_STOCK_FROM_LIST = 'REMOVE_STOCK_FROM_LIST'
export const INITIAL_STOCK_LIST = "INITIAL_STOCK_LIST"

//NEWS ACTIONS
export const LOADING_NEWS = 'LOADING_NEWS'
export const FETCH_NEWS = 'FETCH_NEWS'